import bodyParser from "body-parser";

export default function (app) {
  app.set("port", process.env.PORT || 3000);
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));
}

var rules = require("./rules.json");

// Logic on checking the property type
function checkPropertyType(res, name, type, obj, itemType = "string") {
  if (type == "integer") {
    type = "number";
    if (isNaN(obj[name])) res.status(400).send(name + " must be a " + type);
  }

  if (type == "array") {
    if (name in obj) {
      var arr = obj[name];
      if (itemType == "integer") itemType = "number";
      if (Array.isArray(arr)) {
        for (var i = 0; i < arr.length; i++) {
          if (itemType == "number"){
            if (isNaN(arr[i]))
            res
            .status(400)
            .send(name + " must be an array consisting of " + itemType);
          }
          else if (typeof arr[i] != itemType || !isNaN(arr[i]))
            res
              .status(400)
              .send(name + " must be an array consisting of " + itemType);
        }
      } else res.status(400).send(name + " must be an array");
    }
  } else if (name in obj && typeof obj[name] != type)
    res.status(400).send(name + " must be a " + type);
}

// Iterate over parameters and check every properties type
function checkPropertiesType(res, rulesProperties, obj, type) {
  if (type == "body") {
    for (const [key, value] of Object.entries(rulesProperties)) {
      var type = value["type"];
      checkPropertyType(res, key, type, obj);
    }
  } else if (type == "query") {
    for (var i = 0; i < rulesProperties.length; i++) {
      var name = rulesProperties[i]["name"];
      var type = rulesProperties[i]["type"];

      if (name in obj) {
        if (type == "integer") obj[name] = parseInt(obj[name]);

        if (type == "array") {
          obj[name] = obj[name].split(",");
          var itemType = rulesProperties[i]["items"]["type"];
          checkPropertyType(res, name, type, obj, itemType);
        } else checkPropertyType(res, name, type, obj);
      }
    }
  }
}

// Check if there is any unknown keys in parameters
function checkPropertiesKeys(res, rulesProperties, obj, type) {
  if (type == "body") {
    var keys = Object.keys(rulesProperties);
  } else if (type == "query") {
    var keys = [];
    for (var i = 0; i < rulesProperties.length; i++)
      keys.push(rulesProperties[i]["name"]);
  }
  for (const key of Object.keys(obj)) {
    if (!keys.includes(key))
      res.status(400).send("Unknown key " + key + " in parameters");
  }
}

/**
 * TBD: middleware that checks the request body and querystring against the
 * existing json configuration in order to ensure that:
 * all required parameters are present
 * all parameters are of the correct type
 * non-existing parameters are blocked
 *
 * @throws throw a 400 code error with a relevant error message
 *
 * @param {object} req request object generated by express
 * @param {object} res response object generated by express
 * @param {function} next middleware function
 */
export const checkAgainstRules = (req, res, next) => {
  // TBD

  var route = req.originalUrl.split("?")[0];
  if (route[route.length - 1] == "/") route = route.slice(0, route.length - 1);
  var method = req.method.toLowerCase();

  var parameters = rules["paths"][route][method]["parameters"];

  var ruleMethod = Object.keys(rules["paths"][route])[0];

  switch (route) {
    case "/api/account/role":
      if (method != ruleMethod) res.status(400).send("Wrong method");
      break;
    case "/api/account/profile":
      if (method != "put") res.status(400).send("Wrong method");
      var body = req.body;
      var bodyLength = Object.keys(body).length;
      if (bodyLength == 0) res.status(400).send("Body cannot be empty");

      var bodyProperties = parameters[0]["schema"]["properties"];
      checkPropertiesKeys(res, bodyProperties, body, "body");
      checkPropertiesType(res, bodyProperties, body, "body");

      break;
    case "/api/account/member":
      if (method != ruleMethod) res.status(400).send("Wrong method");

      var body = req.body;
      var bodyLength = Object.keys(body).length;

      if (!("account_id" in body))
        res.status(400).send("account_id must be provided");

      var bodyProperties = parameters[0]["schema"]["properties"];
      checkPropertiesKeys(res, bodyProperties, body, "body");
      checkPropertiesType(res, bodyProperties, body, "body");

      break;
    case "/api/account/search":
      if (method != ruleMethod) res.status(400).send("Wrong method");

      var query = req.query;

      checkPropertiesKeys(res, parameters, query, "query");
      checkPropertiesType(res, parameters, query, "query");

      break;
  }

  return next();
};
